version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
      POSTGRES_DB: gym
    ports:
      - "5432:5432"
  backend:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: pgsql
    ports:
      - "8080:8080"
